# Generated by Django 5.2.7 on 2025-10-20 16:59

import pubbudgetapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('country_code', models.CharField(db_index=True, max_length=2)),
                ('media', models.FileField(blank=True, null=True, upload_to=pubbudgetapp.models.ad_media_upload_to)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('media_mime', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
